// angular-modern/src/app/app.component.ts
import {Component} from '@angular/core';
import bulletTrain from 'bullet-train-client';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'app';
  has_loaded = false;
  instant_messaging = false;
  font_size = 12;

  constructor() {
    var environmentID = "QjgYur4LQTwe5HpvbvhpzK";
    bulletTrain.init({
      environmentID: environmentID,
      onChange: () => {
        this.has_loaded = true;
        this.instant_messaging = bulletTrain.hasFeature("instant_messaging");
        this.font_size = bulletTrain.getValue("font_size");
        console.log("Received flags", bulletTrain.getAllFlags())
      }
    });
  }
}

<!--The content below is only a placeholder and can be replaced.-->
<div style="text-align:center">
  <div *ngIf="has_loaded">
    <div *ngIf="instant_messaging">
      You have the instant messaging feature
    </div>
    <div *ngIf="!instant_messaging">
      You do not have the feature
    </div>
    <span [ngStyle]="{ fontSize: font_size + 'px' }">
    Font size controlled by BulletTrain
    </span>
  </div>
  <div *ngIf="!has_loaded">
    Loading
  </div>
</div>

// react-redux/src/components/App.js
import React, { Component } from 'react'

export default ({ has_loaded, instant_messaging, font_size }) => (
  <div>
    {has_loaded && (
      <div>
        {instant_messaging ? (
          <div>
            You have the instant messaging feature
          </div>
        ) : (
          <div v-else>
            You do not have the feature
          </div>
        )}
        <span style={{ fontSize: font_size }}>
            Font size controlled by BulletTrain
        </span>
      </div>
    )}
  </div>
)
